# alias
source "$HOME/.zsh_aliases"

# prompt
eval "$(starship init zsh)"

# ssh agent
eval "$(ssh-agent -s)" > /dev/null 2>&1
ssh-add  "$HOME/.ssh/id_ed25519" > /dev/null 2>&1

# fzf
source <(fzf --zsh)

function zed() { zeditor "$@" }

function fr() {
  if [ $# -eq 0 ]; then
    echo "Usage: fr <command> [args...]"
    return 1
  fi

  local cmd=$1
  shift

  # Run fzf, if it returns something, run the command with that
  local selection
  selection=$(fzf)

  [ -n "$selection" ] && "$cmd" "$@" "$selection"
}

# takes a video and turns it into a codec that whatsapp accepts
function whatsappify() {
  if [[ -z "$1" ]]; then
    echo "Usage: whatsappify <input_video>"
    return 1
  fi

  input="$1"
  filename="${input%.*}"
  output="${filename}_whatsapp.mp4"

  ffmpeg -i "$input" \
    -vf "scale=w=640:h=trunc(ow/a/2)*2" \
    -c:v libx264 -preset fast -crf 28 \
    -c:a aac -b:a 96k -movflags +faststart \
    -max_muxing_queue_size 1024 \
    "$output"

  echo "Converted video saved as: $output"
}

export EDITOR="nvim";
export FZF_DEFAULT_COMMAND="fd . . --exclude '.*' --maxdepth=10";
export FZF_DEFAULT_OPTS='--preview "bat --style=numbers --color=always --line-range=:500 {}" --delimiter /'
export NIXPKGS_ALLOW_UNFREE=1

# vim mode
bindkey -v

# Auto‑attach or create tmux only when launched from Alacritty
if [[ -z "$TMUX" ]]; then
  # Find parent PID
  parent_pid="$PPID"
  # Get its command name
  parent_cmd="$(< /proc/$parent_pid/comm 2>/dev/null || echo '')"
  if [[ "$parent_cmd" == "alacritty" ]]; then
    if tmux ls &>/dev/null; then
      exec tmux attach-session
    else
      exec tmux new -s Default
    fi
  fi
fi

export PATH="$HOME/.npm-global/bin:$HOME/.cargo/bin:$PATH"
