set -g prefix C-p
unbind C-b

bind C-p send-prefix

# move splits using alt arrows
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind v split-window -h   # Ctrl-b v vert split

bind h split-window -v   # Ctrl-b s horz split

bind q kill-pane # q quits current split

setw -g mouse on

set-option -g detach-on-destroy off